on: [workflow_dispatch]

jobs:
  job:
    runs-on: ubuntu-latest
    name: CustomActionWithJS
    steps:
    - name: Set Greeting
      id: GitHubActionsWorkshopCustomAction
      uses: jmfloreszazo/GitHubActionsWorkshopCustomAction@v1
      with:
        greeting: 'Hi custom action!'
    - name: Output
      run: echo "Output is ${{ steps.GitHubActionsWorkshopCustomAction.outputs.timeofmessage }}"
